# $OpenBSD$

COMMENT=		Motorola and Intel hex to binary conversion tool

V=			2.5
DISTNAME=		Hex2bin-${V}
PKGNAME=		hex2bin-${V}
CATEGORIES=		devel
HOMEPAGE=		http://hex2bin.sourceforge.net/

# BSD
PERMIT_PACKAGE=		yes

MASTER_SITES=		${MASTER_SITE_SOURCEFORGE:=hex2bin/}
EXTRACT_SUFX=		.tar.bz2

WANTLIB+=		c

USE_GMAKE=		Yes

.include <bsd.port.mk>
