# $OpenBSD$

COMMENT=	tiling window manager

V=		1.0
DISTNAME=	sdorfehs-${V}
GH_TAGNAME=	v${V}
GH_ACCOUNT=	jcs
GH_PROJECT=	sdorfehs

CATEGORIES=	x11

MAINTAINER=	joshua stein <jcs@jcs.org>

# GPLv2
PERMIT_PACKAGE=	Yes

WANTLIB=	c X11 Xft Xrandr Xtst

.include <bsd.port.mk>
