# $OpenBSD$

COMMENT=	Ruby version redirection shim

GH_ACCOUNT=	jcs
GH_PROJECT=	openbsd-ruby-shims
GH_TAGNAME=	v1
CATEGORIES=	devel

MAINTAINER=	joshua stein <jcs@openbsd.org>

# ISC
PERMIT_PACKAGE=	Yes

NO_TEST=	Yes

.include <bsd.port.mk>
