# $OpenBSD$

COMMENT=	common HMAC interface

DISTNAME=	ruby-hmac-0.4.0
PKGNAME=	hmac-0.4.0
CATEGORIES=	security net

HOMEPAGE=	http://rubygems.org/gems/ruby-hmac

# MIT
PERMIT_PACKAGE=	yes

MODULES=	lang/ruby
CONFIGURE_STYLE= ruby gem

.include <bsd.port.mk>
