# $OpenBSD$

COMMENT=	common HMAC interface

DISTNAME=	ruby-hmac-0.4.0
PKGNAME=	hmac-0.4.0
CATEGORIES=	security net

HOMEPAGE=	http://rubygems.org/gems/ruby-hmac

# mit
PERMIT_PACKAGE_CDROM=	Yes
PERMIT_PACKAGE_FTP=	Yes

MODULES=	lang/ruby
CONFIGURE_STYLE= ruby gem

.include <bsd.port.mk>
