# $OpenBSD$

COMMENT=		disassembler for the Zilog Z80 microprocessor

DISTNAME=		z80dasm-1.2.0
CATEGORIES=		devel
HOMEPAGE=		https://www.tablix.org/~avian/blog/articles/z80dasm/

# GPLv2
PERMIT_PACKAGE=		yes

MASTER_SITES=		https://www.tablix.org/~avian/z80dasm/

CONFIGURE_STYLE=	gnu

WANTLIB+=		c

.include <bsd.port.mk>
