# $OpenBSD$

COMMENT=	x11 prompt to tap ssh cards or keys

V=		1.0
DISTNAME=	ssh-agent-card-prompt-${V}
GH_TAGNAME=	v${V}
GH_ACCOUNT=	jcs
GH_PROJECT=	ssh-agent-card-prompt

CATEGORIES=	x11

MAINTAINER=	joshua stein <jcs@openbsd.org>

# ISC
PERMIT_PACKAGE=	yes

WANTLIB+=	X11 Xft c

.include <bsd.port.mk>
