COMMENT=	tool for reading and writing to Rockchip devices

GH_ACCOUNT =	rockchip-linux
GH_PROJECT =	rkdeveloptool
GH_COMMIT =	304f073752fd25c854e1bcf05d8e7f925b1f4e14
DISTNAME =	${GH_PROJECT}-0.20250307

CATEGORIES =	sysutils

MAINTAINER=	joshua stein <jcs@jcs.org>

# GPLv2
PERMIT_PACKAGE=	yes

AUTOCONF_VERSION= 2.69
AUTOMAKE_VERSION= 1.16
CONFIGURE_STYLE=  gnu autoreconf

LIB_DEPENDS =	devel/libusb1

.include <bsd.port.mk>
