# $OpenBSD$

COMMENT=	wallpaper setting utility

DISTNAME=	hsetroot-1.0.2
CATEGORIES=	x11

# GPLv2
PERMIT_PACKAGE_CDROM=Yes

WANTLIB=	Imlib2 c X11

MASTER_SITES=	${_MASTER_SITE_NETBSD}

LIB_DEPENDS=	graphics/imlib2

CONFIGURE_STYLE=gnu

.include <bsd.port.mk>
