# $OpenBSD$

COMMENT=	dynamically control xterm properties

DISTNAME=	xtermcontrol-3.2
CATEGORIES=	x11

# GPL
PERMIT_PACKAGE=	yes

WANTLIB=	c

MASTER_SITES=	http://thrysoee.dk/xtermcontrol/

CONFIGURE_STYLE= gnu

.include <bsd.port.mk>
